- name: Hello World Sample
  hosts: all
  
  roles:
    - role: '../roles/centos-update-role'
    
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Execute the hostname command
      register: hostnameoutput
      command: "hostname"

    - debug:
          var: hostnameoutput.stdout_lines
